# Generated by Django 6.0.3 on 2026-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=255, unique=True)),
                ('inquire_to', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('info_received_from', models.CharField(max_length=255)),
                ('last_changed_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
    ]
