# Generated by Django 6.0.3 on 2026-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brandentry_last_changed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandentry',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
