# Generated by Django 6.0.3 on 2026-03-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brandentry_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandentry',
            name='info_received_from',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
