# Generated by Django 6.0.3 on 2026-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brandentry_info_received_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandentry',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
