# Generated by Django 6.0.3 on 2026-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_brandentry_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandentry',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
        migrations.AddConstraint(
            model_name='brandentry',
            constraint=models.CheckConstraint(condition=models.Q(('logo__isnull', False), models.Q(('logo', ''), _negated=True), ('logo_image__isnull', False), models.Q(('logo_image', ''), _negated=True), _negated=True), name='brandentry_only_one_logo_source'),
        ),
    ]
