# Generated by Django 6.0.3 on 2026-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brandentry_logo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandentry',
            name='search_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
